openwide_agenda_list_json:
    path:     /agenda/list/events.json
    defaults: { _controller: OpenWideAgendaBundle:Json:eventsListJSON, _format: json }
    requirements: { _format: (xml|json), _method: GET }
