parameters:
    openwide_agenda.fetch_by_legacy.class: 'OpenWide\AgendaBundle\Helper\FetchByLegacy'

services:
    openwide_agenda.fetch_by_legacy:
        class: %openwide_agenda.fetch_by_legacy.class%
        calls:
            - [ setContainer,[ @service_container ] ]
